version: "3"
services:
    mongodb:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        command:
            - mongod
    punch:
        build: .
        environment:
            - NODE_ENV=production
            - MONGO_DATABASE=mongodb://mongodb/unique
        ports:
            - 7012:7012
        links:
            - mongodb
        depends_on:
            - mongodb
